namespace GuitarConfigurator.NetCore.Configuration.Types;

public enum DpadType
{
    Wii,
    WiiUp,
    WiiUpDown,
    WiiUpDownLeft,
    WiiUpDownLeftRight,
    WiiUpDownRight,
    WiiUpLeft,
    WiiUpLeftRight,
    WiiUpRight,
    WiiDown,
    WiiDownLeft,
    WiiDownLeftRight,
    WiiDownRight,
    WiiLeft,
    WiiLeftRight,
    WiiRight,
    Ps2,
    Ps2Up,
    Ps2UpDown,
    Ps2UpDownLeft,
    Ps2UpDownLeftRight,
    Ps2UpDownRight,
    Ps2UpLeft,
    Ps2UpLeftRight,
    Ps2UpRight,
    Ps2Down,
    Ps2DownLeft,
    Ps2DownLeftRight,
    Ps2DownRight,
    Ps2Left,
    Ps2LeftRight,
    Ps2Right
}