using System.ComponentModel;

namespace GuitarConfigurator.NetCore.Configuration.Types;

public enum UsbHostInputType
{
    X,
    A,
    B,
    Y,
    LeftShoulder,
    RightShoulder,
    Kick1,
    Kick2,
    Back,
    Start,
    LeftThumbClick,
    RightThumbClick,
    Guide,
    Capture,
    LeftBlue = 15,
    LeftRed,
    LeftGreen,
    RightBlue,
    RightRed,
    RightGreen,
    SoloGreen = 22,
    SoloRed,
    SoloYellow,
    SoloBlue,
    SoloOrange,
    Green,
    Red,
    Yellow,
    Blue,
    Orange,
    DpadUp = 35,
    DpadDown,
    DpadLeft,
    DpadRight,
    LeftTrigger,
    RightTrigger,
    LeftStickX,
    LeftStickY,
    RightStickX,
    RightStickY,
    [Description("Dpad Up Pressure")] PressureDPadUp,
    [Description("Dpad Right Pressure")] PressureDPadRight,
    [Description("Dpad Left Pressure")] PressureDPadLeft,
    [Description("Dpad Down Pressure")] PressureDPadDown,
    [Description("L1 Pressure")] PressureL1,
    [Description("R1 Pressure")] PressureR1,
    [Description("Triangle Pressure")] PressureTriangle,
    [Description("Circle Pressure")] PressureCircle,
    [Description("Cross Pressure")] PressureCross,
    [Description("Square Pressure")] PressureSquare,
    RedVelocity,
    YellowVelocity,
    BlueVelocity,
    GreenVelocity,
    OrangeVelocity,
    BlueCymbalVelocity,
    YellowCymbalVelocity,
    GreenCymbalVelocity,
    KickVelocity,
    Whammy,
    Tilt,
    Pickup,
    Slider,
    LeftTableVelocity,
    RightTableVelocity,
    EffectsKnob,
    Crossfader,
    AccelX,
    AccelZ,
    AccelY,
    Gyro,
}