namespace GuitarConfigurator.NetCore.Configuration.Types;

public enum UsbHostInputType
{
    X,
    A,
    B,
    Y,

    LeftShoulder,
    RightShoulder,

    Kick1,
    Kick2,

    Back,
    Start,

    LeftThumbClick,
    RightThumbClick,

    Guide,
    Capture,

    LeftBlue,
    LeftRed,
    LeftGreen,
    RightBlue,
    RightRed,
    RightGreen,
    SoloGreen,
    SoloRed,
    SoloYellow,
    SoloBlue,
    SoloOrange,

    Green,
    Red,
    Yellow,
    Blue,
    Orange,
    DpadUp,
    DpadDown,
    DpadLeft,
    DpadRight,

    LeftTrigger,
    RightTrigger,

    LeftStickX,
    LeftStickY,
    RightStickX,
    RightStickY,

    PressureDpadUp,
    PressureDpadRight,
    PressureDpadLeft,
    PressureDpadDown,
    PressureL1,
    PressureR1,
    PressureTriangle,
    PressureCircle,
    PressureCross,
    PressureSquare,
    RedVelocity,
    YellowVelocity,
    BlueVelocity,
    GreenVelocity,
    OrangeVelocity,
    BlueCymbalVelocity,
    YellowCymbalVelocity,
    GreenCymbalVelocity,
    KickVelocity,
    Whammy,
    Tilt,
    Pickup,
    Slider,
    LeftTableVelocity,
    RightTableVelocity,
    EffectsKnob,
    Crossfader,
    AccelX,
    AccelZ,
    AccelY,
    Gyro,
}